### ISSUE TITLE
Expose semver of package in `User-Agent` header field?

### ISSUE THREAD

**Issue by gracecodes144** [chop-dbhi/data-models-service#1]

**Comment by bruth** [comment]
What is the motivation for this? Why the User-Agent?

**Comment by gracecodes144** [comment]
Motivation described in chop-dbhi/data-models#80

**Comment by gracecodes144** [comment]
User-Agent header seems like the place suggested by several resources I looked at. https://en.wikipedia.org/wiki/User_agent

**Comment by bruth** [comment]
My gut tells me this is the not the place to put it since it feels more like an API version rather than a _server_ version. That being said, how do you want to use this.

**Comment by gracecodes144** [comment]
Basically, I want to use it for debugging purposes and provenance, not to actually negotiate for API version or anything. Where do you think we should put it, in that case?

**Comment by gracecodes144** [comment]
BTW, this seems to be a huge debate I've stumbled onto:

http://www.troyhunt.com/2014/02/your-api-versioning-is-wrong-which-is.html
https://www.mnot.net/blog/2011/10/25/web_api_versioning_smackdown

**Comment by gracecodes144** [comment]
In addition to exposing the _data model_ version being exposed (work in #4, #5, and #6), I think the _service_ version should be exposed as well, since that could alter the output.

**Comment by gracecodes144** [comment]
Working to include this in the output of the DDL generator. See chop-dbhi/data-models-service#9
