### ISSUE TITLE
Incorrect `required` values

### ISSUE THREAD

**Issue by murphyke** [chop-dbhi/data-models-service#18]
http://data-models.origins.link/models/pedsnet/2.1.0?format=json returns incorrect `required` values for some fields.  E.g. for `drug_exposure`, these fields are incorrectly 'true': `drug_exposure_start_time` and `drug_exposure_end_time`.

**Comment by bruth** [comment]
They are wrong in the definition files: https://github.com/chop-dbhi/data-models/blob/master/pedsnet/v2.1/definitions/drug_exposure.csv#L10

**Comment by bruth** [comment]
Moved to data-models repo.
