### ISSUE TITLE
Uniques not generated in schemata?

### ISSUE THREAD

**Issue by gracecodes144** [chop-dbhi/data-models-service#2]
Definition of uniques in pedsnet v1: https://github.com/chop-dbhi/data-models/blob/master/pedsnet/v1/constraints/uniques.csv
Empty uniques list in schemata: http://data-models.origins.link/schemata/pedsnet/v1?format=json

**Comment by bruth** [comment]
[It appears](https://github.com/chop-dbhi/data-models-service/blob/master/parse.go#L250-L300) uniques are not being parsed.. I will fix.

**Comment by bruth** [comment]
More specifically.. https://github.com/chop-dbhi/data-models-service/blob/master/parse.go#L285-L294
